"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useRef, useState, useSyncExternalStore } from "react";
import { conversations, hallNotices, type Conversation, type Message } from "@/data/messaging-data";
import { dashboardLabel, prototypeUser } from "@/data/prototype-user";
import { prototypeStore } from "@/lib/prototype-store";

type View = "personal" | "rooms";
type Overlay = "invite" | "add" | null;
function conversationHref(item: Conversation) { return item.kind === "room" ? `/room/${item.slug}` : `/personal/${item.slug}`; }
function Avatar({ item, large = false }: { item: Pick<Conversation, "initials" | "color">; large?: boolean }) { return <span className={`avatar avatar-${item.color} ${large ? "avatar-large" : ""}`}>{item.initials}</span>; }

const productNavigation = [{ label: dashboardLabel(prototypeUser), icon: "⌂", href: "/" }, { label: "Explore", icon: "⌕", href: "/explore" }, { label: "Marketplace", icon: "◇", href: "/marketplace" }, { label: "Studio", icon: "✦", href: "/studio" }] as const;
function ProductNavigation() { return <nav className="product-nav" aria-label="Tosker"><p className="sidebar-section-label">Tosker</p>{productNavigation.map((item) => <Link key={item.label} href={item.href} className={`product-nav-item tooltip-item ${item.href === "/" ? "active" : ""}`} data-tooltip={item.label}><span aria-hidden="true">{item.icon}</span><strong>{item.label}</strong></Link>)}</nav>; }

function EmptyList({ view }: { view: View }) { return <div className="sidebar-empty"><span aria-hidden="true">{view === "personal" ? "◌" : "⌂"}</span><strong>{view === "personal" ? "Chats are empty." : "No Rooms yet."}</strong><p>{view === "personal" ? "Find a friend and let’s connect." : "Make one and bring some people in."}</p>{view === "rooms" ? <div><Link href="/create">Create a Room</Link><button type="button" disabled>Join a Room</button></div> : null}</div>; }
function ConversationList({ selected, view, fresh, prototypeRooms }: { selected?: Conversation; view: View; fresh: boolean; prototypeRooms: Conversation[] }) {
  const standard = conversations.filter((item) => view === "rooms" ? item.kind === "room" : item.kind !== "room");
  const shown = fresh ? (view === "personal" ? standard.filter((item) => item.kind === "my-room") : prototypeRooms) : standard;
  return <div className="conversation-list">{shown.map((item) => <Link key={item.slug} href={conversationHref(item)} data-tooltip={item.name} className={`conversation-row tooltip-item ${selected?.slug === item.slug ? "active" : ""}`}><Avatar item={item} /><span className="conversation-copy"><span className="conversation-name">{item.name}{item.kind === "my-room" ? <small>Private</small> : null}</span><span className="conversation-preview">{item.preview}</span></span><span className="conversation-trailing"><time>{item.time}</time>{item.unread ? <b>{item.unread}</b> : null}</span></Link>)}{fresh && view === "personal" ? <EmptyList view="personal" /> : null}{fresh && view === "rooms" && shown.length === 0 ? <EmptyList view="rooms" /> : null}</div>;
}
function WalkthroughControls({ fresh }: { fresh: boolean }) { return <div className="walkthrough-controls"><span>Prototype state</span><button type="button" className={fresh ? "active" : ""} onClick={() => prototypeStore.setMode("new")}>Fresh account</button><button type="button" className={!fresh ? "active" : ""} onClick={() => prototypeStore.setMode("demo")}>Demo account</button></div>; }
function AppSidebar({ selected, initialView, collapsed, onToggle, fresh, prototypeRooms }: { selected?: Conversation; initialView: View; collapsed: boolean; onToggle: () => void; fresh: boolean; prototypeRooms: Conversation[] }) {
  const [view, setView] = useState<View>(initialView);
  return <aside className={`messenger-sidebar ${collapsed ? "collapsed" : ""}`}><div className="sidebar-brand"><Link href="/" aria-label="Tosker conversations"><Image className="full-logo" src="/brand/toskerlogo-full-white.svg" alt="Tosker" width={150} height={72} priority /><Image className="mark-logo" src="/brand/toskerlogo-icon-main.svg" alt="" width={44} height={44} priority /></Link><button className="collapse-button tooltip-item" data-tooltip={collapsed ? "Expand sidebar" : "Collapse sidebar"} onClick={onToggle} aria-label={collapsed ? "Expand sidebar" : "Collapse sidebar"}>{collapsed ? "→" : "←"}</button></div><ProductNavigation /><section className="conversation-section"><div className="sidebar-heading"><h1>Conversations</h1><Link href="/create" className="new-room-button tooltip-item" data-tooltip="Create a Room" aria-label="Create a Room">＋</Link></div><div className="view-switch" aria-label="Conversation type"><button className={view === "personal" ? "active" : ""} onClick={() => setView("personal")}><span>Personal</span><i>P</i></button><button className={view === "rooms" ? "active" : ""} onClick={() => setView("rooms")}><span>Rooms</span><i>R</i></button></div><ConversationList selected={selected} view={view} fresh={fresh} prototypeRooms={prototypeRooms} /></section><div className="sidebar-bottom"><div className="utility-nav"><Link href="/settings" className="tooltip-item" data-tooltip="Settings"><span>⚙</span><strong>Settings</strong></Link><Link href="/help" className="tooltip-item" data-tooltip="Help & Feedback"><span>?</span><strong>Help &amp; Feedback</strong></Link></div><button className="profile-row tooltip-item" data-tooltip={`${prototypeUser.name} · Profile`}><span className="avatar avatar-gold">{prototypeUser.initials}</span><span><strong>{prototypeUser.name}</strong><small>{prototypeUser.role}</small></span><b>•••</b></button><WalkthroughControls fresh={fresh} /></div></aside>;
}

function MessageBubble({ message, translated, onTranslate }: { message: Message; translated: boolean; onTranslate: () => void }) { return <article className={`message-row ${message.mine ? "mine" : ""}`} data-message-id={message.id}><span className={`avatar avatar-${message.color}`}>{message.initials}</span><div className="message-column"><div className="message-author"><strong>{message.author}</strong><time>{message.time}</time></div><div className="message-bubble"><p>{message.body}</p>{message.translation ? <button className="translate-button" onClick={onTranslate}>{translated ? "Hide translation" : "Translate"}</button> : null}{translated && message.translation ? <div className="translation"><p>{message.translation}</p><span>Translated from {message.language}</span></div> : null}</div>{!message.mine && message.id.endsWith("1") ? <span className="message-reaction">✦ 2</span> : null}</div></article>; }
function Composer({ name, onSend }: { name: string; onSend: (body: string) => void }) {
  const [value, setValue] = useState(""); const submit = () => { const body = value.trim(); if (!body) return; onSend(body); setValue(""); };
  return <div className="composer-wrap"><div className="composer"><button type="button" className="composer-add" aria-label="Attach something" disabled>＋</button><textarea aria-label={`Message ${name}`} value={value} onChange={(event) => setValue(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); submit(); } }} rows={1} placeholder={`Message ${name}…`} /><button type="button" className="send-button" disabled={!value.trim()} onClick={submit} aria-label="Send message">↑</button></div><span className="composer-hint">Enter to send · Shift + Enter for a new line</span></div>;
}
function ConversationSurface({ conversation, persist }: { conversation: Conversation; persist: boolean }) {
  const [messages, setMessages] = useState(conversation.messages); const [translated, setTranslated] = useState<Set<string>>(() => new Set()); const endRef = useRef<HTMLDivElement>(null);
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: "smooth", block: "end" }); }, [messages]);
  const send = (body: string) => { const message: Message = { id: `local-${crypto.randomUUID()}`, author: prototypeUser.name, initials: prototypeUser.initials, body, time: "Now", color: "gold", mine: true }; setMessages((current) => [...current, message]); if (persist) { if (conversation.kind === "my-room") prototypeStore.addMyRoomMessage(message); else prototypeStore.addRoomMessage(conversation.slug, message); } };
  const mockReply = () => setMessages((current) => [...current, { id: `mock-${crypto.randomUUID()}`, author: conversation.kind === "my-room" ? "Tosker" : "Mika", initials: conversation.kind === "my-room" ? "✦" : "MK", body: conversation.kind === "my-room" ? "Saved here for you." : "Mock reply: that sounds good to me — let’s do it.", time: "Now", color: conversation.kind === "my-room" ? "gold" : "pink" }]);
  const toggleTranslation = (id: string) => setTranslated((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; }); const isEmpty = messages.length === 0;
  return <section className="conversation-surface">{isEmpty ? <div className="conversation-empty"><div className="empty-art" aria-hidden="true"><Image src="/brand/toskerlogo-icon-main.svg" alt="" width={78} height={78} priority /><i>✦</i><i>⌁</i></div><p className="eyebrow">{conversation.kind === "my-room" ? "Private · Just you" : "Ready when you are"}</p><h2>{conversation.kind === "my-room" ? "This is your room." : "Quiet in here."}</h2><p>{conversation.kind === "my-room" ? "Links, thoughts, notes — this one’s yours." : "Invite someone or say the first thing."}</p></div> : null}<div className={`message-scroll ${isEmpty ? "is-empty" : ""}`}>{messages.length ? <div className="day-marker"><span>Today</span></div> : null}{messages.map((message) => <MessageBubble key={message.id} message={message} translated={translated.has(message.id)} onTranslate={() => toggleTranslation(message.id)} />)}<div ref={endRef} /></div>{!persist ? <div className="dev-reply"><span>Walkthrough control</span><button type="button" onClick={mockReply}>Simulate reply</button></div> : null}<Composer name={conversation.name} onSend={send} /></section>;
}
function HallSurface({ empty }: { empty: boolean }) { return <section className={`hall-surface ${empty ? "hall-is-empty" : ""}`}><header><div><p className="eyebrow">The notice wall</p><h2>{empty ? "Nothing on the wall yet." : "What everyone needs to know."}</h2><p>{empty ? "Pin the stuff everyone should know." : "Important details stay here instead of disappearing in conversation."}</p></div>{!empty ? <div className="hall-pin-key"><span>⌖</span> Pinned by the group</div> : null}</header>{empty ? <div className="empty-hall-art"><Image src="/brand/toskerlogo-icon-variation.svg" alt="" width={86} height={86} /><span>Room for announcements, decisions, links, and the useful bits.</span></div> : <><div className="notice-list">{hallNotices.map((notice) => <article className={`notice-card notice-${notice.accent} ${notice.pinned ? "pinned" : ""}`} key={notice.id}>{notice.pinned ? <b className="pin" aria-label="Pinned">⌖</b> : null}<span className="notice-icon">{notice.icon}</span><div><small>{notice.category}</small><h3>{notice.title}</h3><p>{notice.body}</p><footer>{notice.author} · {notice.time}</footer></div></article>)}</div><div className="hall-empty"><Image src="/brand/toskerlogo-icon-main.svg" alt="" width={52} height={52} /><div><strong>That’s everything for now.</strong><p>Good news travels fast. Important news stays here.</p></div></div></>}</section>; }

const addItems = [["◒", "Quick Poll", "By Tosker"], ["▦", "Board", "By Tosker"], ["⌖", "Shared Map", "Preview"], ["▧", "Photo Wall", "Marketplace"], ["◷", "Schedule", "By Tosker"], ["♟", "Tiny Game", "Marketplace"]];
function OverlayPanel({ type, roomName, onClose }: { type: Exclude<Overlay, null>; roomName: string; onClose: () => void }) {
  return <div className="overlay-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="overlay-panel" role="dialog" aria-modal="true" aria-labelledby="overlay-title"><button className="overlay-close" onClick={onClose} aria-label="Close">×</button>{type === "invite" ? <><p className="eyebrow">Bring people in</p><h2 id="overlay-title">Invite to {roomName}</h2><p className="overlay-lead">This prototype shows where the invitation flow will live.</p><label className="invite-link"><span>Invite link</span><input readOnly value={`tosker.local/invite/${roomName.toLowerCase().replaceAll(" ", "-")}`} /></label><div className="overlay-actions"><button onClick={() => navigator.clipboard?.writeText(`Invite to ${roomName}`)}>Copy link</button><button disabled>Share</button></div><small className="prototype-note">Prototype only · Links do not resolve yet</small></> : <><p className="eyebrow">Add to Room</p><h2 id="overlay-title">What does this Room need?</h2><p className="overlay-lead">Chat and Hall are just the beginning.</p><div className="add-grid">{addItems.map(([icon, name, source]) => <button key={name} disabled><span>{icon}</span><strong>{name}</strong><small>{source}</small></button>)}</div><Link href="/explore" className="overlay-explore">See more in Explore <span>→</span></Link><small className="prototype-note">Visual prototype · Nothing installs yet</small></>}</section></div>;
}
function ConversationHeader({ conversation, surface, onOverlay }: { conversation: Conversation; surface: "chat" | "hall"; onOverlay: (overlay: Overlay) => void }) { return <header className="conversation-header"><Link href="/" className="mobile-back" aria-label="Back to conversations">←</Link><Avatar item={conversation} large /><div className="active-copy"><h2>{conversation.name}</h2><span>{conversation.context}</span></div>{conversation.kind === "room" ? <><nav aria-label={`${conversation.name} capabilities`}><Link className={surface === "chat" ? "active" : ""} href={`/room/${conversation.slug}`}>Chat</Link><Link className={surface === "hall" ? "active" : ""} href={`/room/${conversation.slug}/hall`}>Hall</Link><button onClick={() => onOverlay("add")} aria-label="Add to Room">＋<small>Add</small></button></nav><div className="room-utilities" aria-label="Room communication previews"><button title="Search" aria-label="Search Room">⌕</button><button title="Voice call — prototype" aria-label="Voice call prototype">◖</button><button title="Video call — prototype" aria-label="Video call prototype">▹</button><button title="Live stream — prototype" aria-label="Live stream prototype">◉</button><button title="Invite people" onClick={() => onOverlay("invite")} aria-label="Invite people">＋</button><button title="More" aria-label="More Room actions">•••</button></div></> : <button className="header-more" aria-label="Conversation options">•••</button>}</header>; }
function toPrototypeConversation(name: string, slug: string, messages: Message[]): Conversation { return { slug, kind: "room", name, initials: name.slice(0, 2).toUpperCase(), color: "blue", preview: messages.at(-1)?.body ?? "Quiet in here", time: "Now", context: "1 person · New Room", messages }; }

export function MessagingApp({ selectedSlug, surface = "chat" }: { selectedSlug?: string; surface?: "chat" | "hall" }) {
  const state = useSyncExternalStore(prototypeStore.subscribe, prototypeStore.getSnapshot, prototypeStore.getServerSnapshot); const fresh = state.mode === "new"; const prototypeRooms = state.rooms.map((room) => toPrototypeConversation(room.name, room.slug, room.messages)); const myRoom = conversations[0];
  const selected = selectedSlug === "my-room" && fresh ? { ...myRoom, messages: state.myRoomMessages } : prototypeRooms.find((room) => room.slug === selectedSlug) ?? conversations.find((conversation) => conversation.slug === selectedSlug); const view: View = selected?.kind === "room" ? "rooms" : "personal"; const [collapsed, setCollapsed] = useState(false); const [overlay, setOverlay] = useState<Overlay>(null); const isPrototypeConversation = fresh && (selected?.kind === "my-room" || prototypeRooms.some((room) => room.slug === selected?.slug));
  return <main className={`messaging-app ${collapsed ? "sidebar-collapsed" : ""} ${selected ? "has-selection" : "list-only"}`}><AppSidebar selected={selected} initialView={view} collapsed={collapsed} onToggle={() => setCollapsed((current) => !current)} fresh={fresh} prototypeRooms={prototypeRooms} /><div className="working-surface">{selected ? <><ConversationHeader conversation={selected} surface={surface} onOverlay={setOverlay} />{surface === "hall" ? <HallSurface empty={isPrototypeConversation} /> : <ConversationSurface key={`${selected.slug}-${fresh}`} conversation={selected} persist={isPrototypeConversation} />}</> : <div className="desktop-welcome"><div className="welcome-orbit"><Image src="/brand/toskerlogo-icon-main.svg" alt="" width={120} height={120} priority /><span>✦</span><span>◌</span><span>⌁</span></div><p className="eyebrow">{dashboardLabel(prototypeUser)}</p><h2>{`Hey ${prototypeUser.name}, let's pick up where you left off`}</h2><p>Choose a conversation or Room from the left</p>{fresh ? <Link href="/personal/my-room" className="button button-primary">Open My Room <span>→</span></Link> : null}</div>}</div>{overlay && selected ? <OverlayPanel type={overlay} roomName={selected.name} onClose={() => setOverlay(null)} /> : null}</main>;
}
