"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useLayoutEffect, useRef, useState, useSyncExternalStore } from "react";
import { conversations, hallNotices, type Conversation, type Message } from "@/data/messaging-data";
import { dashboardLabel, prototypeUser } from "@/data/prototype-user";
import { prototypeStore } from "@/lib/prototype-store";

type View = "personal" | "rooms";
type Overlay = "invite" | "add" | null;

const productNavigation = [{ label: "Explore", icon: "⌕", href: "/explore" }, { label: "Marketplace", icon: "◇", href: "/marketplace" }, { label: "Studio", icon: "✦", href: "/studio" }] as const;
const addItems = [["◒", "Quick Poll", "By Tosker"], ["▦", "Board", "By Tosker"], ["⌖", "Shared Map", "Preview"], ["▧", "Photo Wall", "Marketplace"], ["◷", "Schedule", "By Tosker"], ["⊞", "Subroom", "Concept"], ["♟", "Tiny Game", "Marketplace"]];
const emojis = ["👍", "❤️", "😂", "✨", "👀", "🍜"];

function conversationHref(item: Conversation) { return item.kind === "room" ? `/room/${item.slug}` : `/personal/${item.slug}`; }
function conversationName(item: Conversation) { return item.kind === "my-room" ? dashboardLabel(prototypeUser) : item.name; }
function Avatar({ item, large = false }: { item: Pick<Conversation, "initials" | "color">; large?: boolean }) { return <span className={`avatar avatar-${item.color} avatar-pattern ${large ? "avatar-large" : ""}`}>{item.initials}</span>; }

function ProductNavigation() {
  return <nav className="product-nav" aria-label="Tosker product areas">{productNavigation.map((item) => <Link key={item.label} href={item.href} className="product-nav-item has-tip" data-tip={item.label}><span aria-hidden="true">{item.icon}</span><strong>{item.label}</strong></Link>)}</nav>;
}

function ConversationMenu({ item, onClose }: { item: Conversation; onClose: () => void }) {
  const [confirming, setConfirming] = useState(false);
  const destructiveLabel = item.kind === "room" ? "Delete Room" : "Remove conversation";
  if (confirming) return <div className="confirm-menu" role="alertdialog" aria-label={`${destructiveLabel} confirmation`}><strong>{destructiveLabel} “{conversationName(item)}”?</strong><p>This only affects the local prototype</p><div><button onClick={() => setConfirming(false)}>Cancel</button><button className="danger" onClick={onClose}>{item.kind === "room" ? "Delete" : "Remove"}</button></div></div>;
  const actions = item.kind === "room" ? ["Mark unread", "Mute", "Archive", "Room settings", "Leave Room"] : ["Mark unread", "Mute", "Archive"];
  return <div className="context-menu conversation-context" role="menu">{actions.map((action) => <button role="menuitem" key={action} onClick={onClose}>{action}<small>Prototype</small></button>)}<hr /><button role="menuitem" className="danger" onClick={() => setConfirming(true)}>{destructiveLabel}</button></div>;
}

function ConversationRow({ item, selected }: { item: Conversation; selected?: Conversation }) {
  const [menuOpen, setMenuOpen] = useState(false);
  return <div className={`conversation-row-shell ${selected?.slug === item.slug ? "active" : ""}`} onContextMenu={(event) => { event.preventDefault(); setMenuOpen(true); }}><Link href={conversationHref(item)} data-tip={conversationName(item)} className="conversation-row has-tip"><Avatar item={item} /><span className="conversation-copy"><span className="conversation-name">{conversationName(item)}{item.kind === "my-room" ? <small>Private</small> : null}</span><span className="conversation-preview">{item.preview}</span></span><span className="conversation-trailing"><time>{item.time}</time>{item.unread ? <b>{item.unread}</b> : null}</span></Link><button className="row-options has-tip" data-tip="Conversation options" aria-label={`Options for ${conversationName(item)}`} onClick={() => setMenuOpen((open) => !open)}>•••</button>{menuOpen ? <ConversationMenu item={item} onClose={() => setMenuOpen(false)} /> : null}</div>;
}

function EmptyList({ view }: { view: View }) {
  return <div className="sidebar-empty"><span aria-hidden="true">{view === "personal" ? "◌" : "⌂"}</span><strong>{view === "personal" ? "Chats are empty" : "No Rooms yet"}</strong><p>{view === "personal" ? "Find a friend and let’s connect" : "Make one and bring some people in"}</p>{view === "rooms" ? <div><Link href="/create">Create a Room</Link><button type="button" disabled>Join a Room</button></div> : null}</div>;
}

function ConversationList({ selected, view, fresh, prototypeRooms, query }: { selected?: Conversation; view: View; fresh: boolean; prototypeRooms: Conversation[]; query: string }) {
  const standard = conversations.filter((item) => view === "rooms" ? item.kind === "room" : item.kind !== "room");
  const available = fresh ? (view === "personal" ? standard.filter((item) => item.kind === "my-room") : prototypeRooms) : standard;
  const normalized = query.trim().toLowerCase();
  const shown = normalized ? available.filter((item) => conversationName(item).toLowerCase().includes(normalized)) : available;
  return <div className="conversation-list">{shown.map((item) => <ConversationRow key={item.slug} item={item} selected={selected} />)}{normalized && shown.length === 0 ? <p className="search-empty">Nothing matches “{query.trim()}”</p> : null}{!normalized && fresh && view === "personal" ? <EmptyList view="personal" /> : null}{!normalized && fresh && view === "rooms" && shown.length === 0 ? <EmptyList view="rooms" /> : null}</div>;
}

function WalkthroughControls({ fresh }: { fresh: boolean }) { return <div className="walkthrough-controls"><span>Prototype state</span><button type="button" className={fresh ? "active" : ""} onClick={() => prototypeStore.setMode("new")}>Fresh account</button><button type="button" className={!fresh ? "active" : ""} onClick={() => prototypeStore.setMode("demo")}>Demo account</button></div>; }

function AppSidebar({ selected, initialView, collapsed, onToggle, fresh, prototypeRooms }: { selected?: Conversation; initialView: View; collapsed: boolean; onToggle: () => void; fresh: boolean; prototypeRooms: Conversation[] }) {
  const [view, setView] = useState<View>(initialView);
  const [query, setQuery] = useState("");
  const searchRef = useRef<HTMLInputElement>(null);
  return <aside className={`messenger-sidebar ${collapsed ? "collapsed" : ""}`}><div className="sidebar-brand"><Link href="/personal/my-room" aria-label={`${dashboardLabel(prototypeUser)} conversations`}><Image className="full-logo" src="/brand/toskerlogo-full-white.svg" alt="Tosker" width={150} height={72} priority /><Image className="mark-logo" src="/brand/toskerlogo-icon-main.svg" alt="" width={44} height={44} priority /></Link><button className="collapse-button has-tip" data-tip={collapsed ? "Expand sidebar" : "Collapse sidebar"} onClick={onToggle} aria-label={collapsed ? "Expand sidebar" : "Collapse sidebar"}>{collapsed ? "→" : "←"}</button></div><ProductNavigation /><section className="conversation-section"><div className="view-switch" aria-label="Conversation type"><button className={`has-tip ${view === "personal" ? "active" : ""}`} data-tip="Personal" onClick={() => { setView("personal"); setQuery(""); }}><i aria-hidden="true">◉</i><span>Personal</span></button><button className={`has-tip ${view === "rooms" ? "active" : ""}`} data-tip="Rooms" onClick={() => { setView("rooms"); setQuery(""); }}><i aria-hidden="true">▦</i><span>Rooms</span></button></div><div className="sidebar-search">{collapsed ? <button className="has-tip" data-tip="Search" aria-label="Search conversations" onClick={() => { onToggle(); requestAnimationFrame(() => searchRef.current?.focus()); }}>⌕</button> : <><span aria-hidden="true">⌕</span><input ref={searchRef} value={query} onChange={(event) => setQuery(event.target.value)} aria-label={`Search ${view}`} placeholder={view === "rooms" ? "Find a Room" : "Find a conversation"} /><Link href="/create" className="has-tip" data-tip="Create a Room" aria-label="Create a Room">＋</Link></>}</div><ConversationList selected={selected} view={view} fresh={fresh} prototypeRooms={prototypeRooms} query={query} /></section><div className="sidebar-bottom"><div className="utility-nav"><Link href="/settings" className="has-tip" data-tip="Settings"><span>⚙</span><strong>Settings</strong></Link><Link href="/help" className="has-tip" data-tip="Help & Feedback"><span>?</span><strong>Help &amp; Feedback</strong></Link></div><button className="profile-row has-tip" data-tip={`${prototypeUser.displayName} · Profile`}><span className="avatar avatar-gold">{prototypeUser.initials}</span><span><strong>{prototypeUser.displayName}</strong><small>{prototypeUser.role}</small></span><b>•••</b></button><WalkthroughControls fresh={fresh} /></div></aside>;
}

function linkBody(body: string) {
  const match = body.match(/https?:\/\/\S+/);
  if (!match) return body;
  const [before, after] = body.split(match[0]);
  return <>{before}<a href={match[0]} target="_blank" rel="noreferrer">{match[0]}</a>{after}</>;
}

function MessageBubble({ message, translated, onTranslate, onDelete }: { message: Message; translated: boolean; onTranslate: () => void; onDelete: () => void }) {
  const [menuOpen, setMenuOpen] = useState(false);
  const [confirming, setConfirming] = useState(false);
  return <article className={`message-row ${message.mine ? "mine" : ""}`} data-message-id={message.id} onContextMenu={(event) => { event.preventDefault(); setMenuOpen(true); }}><span className={`avatar avatar-${message.color} avatar-pattern`}>{message.initials}</span><div className="message-column"><div className="message-author"><strong>{message.author}</strong><time>{message.time}</time></div><div className="message-content"><div className="message-bubble">{message.replyTo ? <blockquote>{message.replyTo}</blockquote> : null}<p>{linkBody(message.body)}</p>{message.attachment ? <div className={`message-attachment attachment-${message.attachment.type}`}><span>{message.attachment.type === "image" ? "▧" : "▤"}</span><div><strong>{message.attachment.name}</strong><small>{message.attachment.meta}</small></div></div> : null}{message.translation ? <button className="translate-button" onClick={onTranslate}>{translated ? "Hide translation" : "Translate"}</button> : null}{translated && message.translation ? <div className="translation"><p>{message.translation}</p><span>Translated from {message.language}</span></div> : null}</div><button className="message-options has-tip" data-tip="Message actions" aria-label={`Actions for ${message.author}'s message`} onClick={() => setMenuOpen((open) => !open)}>•••</button></div>{message.id.endsWith("01") || message.id.endsWith("09") ? <span className="message-reaction">✨ 2</span> : null}{menuOpen ? <div className="context-menu message-context" role="menu"><button onClick={() => setMenuOpen(false)}>Reply<small>Prototype</small></button><button onClick={() => setMenuOpen(false)}>React<small>Prototype</small></button><button onClick={() => { navigator.clipboard?.writeText(message.body); setMenuOpen(false); }}>Copy text</button><button onClick={() => setMenuOpen(false)}>Save<small>Prototype</small></button>{message.mine ? <button onClick={() => setMenuOpen(false)}>Edit<small>Prototype</small></button> : null}<hr /><button className="danger" onClick={() => { setMenuOpen(false); setConfirming(true); }}>{message.mine ? "Delete" : "Remove message"}</button></div> : null}{confirming ? <div className="confirm-menu message-confirm" role="alertdialog"><strong>{message.mine ? "Delete this message?" : "Remove this message?"}</strong><p>This only affects the current local session</p><div><button onClick={() => setConfirming(false)}>Cancel</button><button className="danger" onClick={onDelete}>{message.mine ? "Delete" : "Remove"}</button></div></div> : null}</div></article>;
}

function Composer({ name, onSend }: { name: string; onSend: (body: string, attachment?: Message["attachment"]) => void }) {
  const [value, setValue] = useState("");
  const [emojiOpen, setEmojiOpen] = useState(false);
  const imageRef = useRef<HTMLInputElement>(null);
  const fileRef = useRef<HTMLInputElement>(null);
  const submit = () => { const body = value.trim(); if (!body) return; onSend(body); setValue(""); };
  const attach = (file: File | undefined, type: "image" | "file") => { if (!file) return; onSend(type === "image" ? "Shared an image" : "Shared a file", { type, name: file.name, meta: `${type === "image" ? "Local image" : "Local file"} · Prototype only` }); };
  return <div className="composer-wrap"><div className="composer"><div className="composer-tools"><button type="button" className="has-tip" data-tip="Upload image" aria-label="Upload image" onClick={() => imageRef.current?.click()}>▧</button><button type="button" className="has-tip" data-tip="Upload file" aria-label="Upload file" onClick={() => fileRef.current?.click()}>▤</button><button type="button" className="has-tip" data-tip="Add emoji" aria-label="Add emoji" onClick={() => setEmojiOpen((open) => !open)}>☺</button></div><input ref={imageRef} hidden type="file" accept="image/*" onChange={(event) => attach(event.target.files?.[0], "image")} /><input ref={fileRef} hidden type="file" onChange={(event) => attach(event.target.files?.[0], "file")} /><textarea aria-label={`Message ${name}`} value={value} onChange={(event) => setValue(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); submit(); } }} rows={1} placeholder={`Message ${name}…`} /><button type="button" className="send-button has-tip" data-tip="Send message" disabled={!value.trim()} onClick={submit} aria-label="Send message">↑</button>{emojiOpen ? <div className="emoji-picker" aria-label="Emoji picker">{emojis.map((emoji) => <button key={emoji} onClick={() => { setValue((current) => `${current}${emoji}`); setEmojiOpen(false); }}>{emoji}</button>)}</div> : null}</div><span className="composer-hint">Enter to send · Shift + Enter for a new line</span></div>;
}

function ConversationSurface({ conversation, persist }: { conversation: Conversation; persist: boolean }) {
  const [messages, setMessages] = useState(conversation.messages);
  const [translated, setTranslated] = useState<Set<string>>(() => new Set());
  const scrollRef = useRef<HTMLDivElement>(null);
  const stayAtBottom = useRef(true);
  useLayoutEffect(() => { const element = scrollRef.current; if (element) element.scrollTop = element.scrollHeight; }, [conversation.slug]);
  useEffect(() => { const element = scrollRef.current; if (element && stayAtBottom.current) element.scrollTo({ top: element.scrollHeight, behavior: "smooth" }); }, [messages]);
  const send = (body: string, attachment?: Message["attachment"]) => { const message: Message = { id: `local-${crypto.randomUUID()}`, author: prototypeUser.displayName, initials: prototypeUser.initials, body, attachment, time: "Now", color: "gold", mine: true }; stayAtBottom.current = true; setMessages((current) => [...current, message]); if (persist) { if (conversation.kind === "my-room") prototypeStore.addMyRoomMessage(message); else prototypeStore.addRoomMessage(conversation.slug, message); } };
  const mockReply = () => setMessages((current) => [...current, { id: `mock-${crypto.randomUUID()}`, author: conversation.kind === "my-room" ? "Tosker" : "Mika", initials: conversation.kind === "my-room" ? "✦" : "MK", body: conversation.kind === "my-room" ? "Saved here for you" : "That sounds good to me — let’s do it", time: "Now", color: conversation.kind === "my-room" ? "gold" : "pink" }]);
  const toggleTranslation = (id: string) => setTranslated((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });
  const isEmpty = messages.length === 0;
  return <section className="conversation-surface">{isEmpty ? <div className="conversation-empty"><div className="empty-art" aria-hidden="true"><Image src="/brand/toskerlogo-icon-main.svg" alt="" width={78} height={78} priority /><i>✦</i><i>⌁</i></div><p className="eyebrow">{conversation.kind === "my-room" ? "Private · Just you" : "Ready when you are"}</p><h2>{conversation.kind === "my-room" ? `This is ${prototypeUser.displayName}'s Dashboard` : "Quiet in here"}</h2><p>{conversation.kind === "my-room" ? "Links, thoughts, notes — this one’s yours" : "Invite someone or say the first thing"}</p></div> : null}<div ref={scrollRef} onScroll={(event) => { const element = event.currentTarget; stayAtBottom.current = element.scrollHeight - element.scrollTop - element.clientHeight < 80; }} className={`message-scroll ${isEmpty ? "is-empty" : ""}`}>{messages.length ? <div className="day-marker"><span>Today</span></div> : null}{messages.map((message) => <MessageBubble key={message.id} message={message} translated={translated.has(message.id)} onTranslate={() => toggleTranslation(message.id)} onDelete={() => setMessages((current) => current.filter((item) => item.id !== message.id))} />)}</div>{!persist ? <div className="dev-reply"><span>Walkthrough control</span><button type="button" onClick={mockReply}>Simulate reply</button></div> : null}<Composer name={conversationName(conversation)} onSend={send} /></section>;
}

function HallSurface({ empty }: { empty: boolean }) { return <section className={`hall-surface ${empty ? "hall-is-empty" : ""}`}><header><div><p className="eyebrow">The notice wall</p><h2>{empty ? "Nothing on the wall yet" : "What everyone needs to know"}</h2><p>{empty ? "Pin the stuff everyone should know" : "Important details stay here instead of disappearing in conversation"}</p></div>{!empty ? <div className="hall-pin-key has-tip" data-tip="Pinned items"><span>⌖</span> Pinned by the group</div> : null}</header>{empty ? <div className="empty-hall-art"><Image src="/brand/toskerlogo-icon-variation.svg" alt="" width={86} height={86} /><span>Room for announcements, decisions, links, and the useful bits</span></div> : <><div className="notice-list">{hallNotices.map((notice) => <article className={`notice-card notice-${notice.accent} ${notice.pinned ? "pinned" : ""}`} key={notice.id}>{notice.pinned ? <b className="pin has-tip" data-tip="Pinned" aria-label="Pinned">⌖</b> : null}<span className="notice-icon">{notice.icon}</span><div><small>{notice.category}</small><h3>{notice.title}</h3><p>{notice.body}</p><footer>{notice.author} · {notice.time}</footer></div></article>)}</div><div className="hall-empty"><Image src="/brand/toskerlogo-icon-main.svg" alt="" width={52} height={52} /><div><strong>That’s everything for now</strong><p>Good news travels fast. Important news stays here</p></div></div></>}</section>; }

function OverlayPanel({ type, roomName, onClose }: { type: Exclude<Overlay, null>; roomName: string; onClose: () => void }) { return <div className="overlay-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="overlay-panel" role="dialog" aria-modal="true" aria-labelledby="overlay-title"><button className="overlay-close has-tip" data-tip="Close" onClick={onClose} aria-label="Close">×</button>{type === "invite" ? <><p className="eyebrow">Bring people in</p><h2 id="overlay-title">Invite to {roomName}</h2><p className="overlay-lead">This prototype shows where the invitation flow will live</p><label className="invite-link"><span>Invite link</span><input readOnly value={`tosker.local/invite/${roomName.toLowerCase().replaceAll(" ", "-")}`} /></label><div className="overlay-actions"><button onClick={() => navigator.clipboard?.writeText(`Invite to ${roomName}`)}>Copy link</button><button disabled>Share</button></div><small className="prototype-note">Prototype only · Links do not resolve yet</small></> : <><p className="eyebrow">Add to Room</p><h2 id="overlay-title">What does this Room need?</h2><p className="overlay-lead">Chat and Hall are just the beginning</p><div className="add-grid">{addItems.map(([icon, name, source]) => <button key={name} disabled><span>{icon}</span><strong>{name}</strong><small>{source}</small></button>)}</div><Link href="/explore" className="overlay-explore">See more in Explore <span>→</span></Link><small className="prototype-note">Visual prototype · Nothing installs yet</small></>}</section></div>; }

function ConversationHeader({ conversation, surface, onOverlay }: { conversation: Conversation; surface: "chat" | "hall"; onOverlay: (overlay: Overlay) => void }) {
  const [utility, setUtility] = useState<string | null>(null);
  const action = (label: string, icon: string) => <button className="has-tip" data-tip={label} aria-label={label} onClick={() => setUtility(label)}>{icon}</button>;
  return <header className="conversation-header"><Link href="/" className="mobile-back" aria-label="Back to conversations">←</Link><Avatar item={conversation} large /><div className="active-copy"><h2>{conversationName(conversation)}</h2><span>{conversation.context}</span></div>{conversation.kind === "room" ? <><nav aria-label={`${conversation.name} surfaces`}><Link className={surface === "chat" ? "active" : ""} href={`/room/${conversation.slug}`}>Chat</Link><Link className={surface === "hall" ? "active" : ""} href={`/room/${conversation.slug}/hall`}>Hall</Link><button className="has-tip" data-tip="Add to Room" onClick={() => onOverlay("add")} aria-label="Add to Room">＋<small>Add</small></button></nav><div className="room-utilities" aria-label="Room communication previews">{action("Search Room", "⌕")}{action("Start voice call", "◖")}{action("Start video call", "▹")}{action("Go live", "◉")}<button className="has-tip" data-tip="Invite people" onClick={() => onOverlay("invite")} aria-label="Invite people">＋</button>{action("More Room actions", "•••")}</div>{utility ? <div className="header-popover" role="dialog"><strong>{utility}</strong><p>{utility === "More Room actions" ? "Pinned items and Room settings will live here" : "Prototype placement only"}</p><button onClick={() => setUtility(null)}>Close</button></div> : null}</> : <button className="header-more has-tip" data-tip="Conversation options" onClick={() => setUtility("Conversation options")} aria-label="Conversation options">•••</button>}</header>;
}

function toPrototypeConversation(name: string, slug: string, messages: Message[]): Conversation { return { slug, kind: "room", name, initials: name.slice(0, 2).toUpperCase(), color: "blue", preview: messages.at(-1)?.body ?? "Quiet in here", time: "Now", context: "1 person · New Room", messages }; }

export function MessagingApp({ selectedSlug, surface = "chat" }: { selectedSlug?: string; surface?: "chat" | "hall" }) {
  const state = useSyncExternalStore(prototypeStore.subscribe, prototypeStore.getSnapshot, prototypeStore.getServerSnapshot);
  const fresh = state.mode === "new";
  const prototypeRooms = state.rooms.map((room) => toPrototypeConversation(room.name, room.slug, room.messages));
  const myRoom = conversations[0];
  const selected = selectedSlug === "my-room" && fresh ? { ...myRoom, messages: state.myRoomMessages } : prototypeRooms.find((room) => room.slug === selectedSlug) ?? conversations.find((conversation) => conversation.slug === selectedSlug);
  const view: View = selected?.kind === "room" ? "rooms" : "personal";
  const [collapsed, setCollapsed] = useState(false);
  const [overlay, setOverlay] = useState<Overlay>(null);
  const isPrototypeConversation = fresh && (selected?.kind === "my-room" || prototypeRooms.some((room) => room.slug === selected?.slug));
  return <main className={`messaging-app ${collapsed ? "sidebar-collapsed" : ""} ${selected ? "has-selection" : "list-only"}`}><AppSidebar selected={selected} initialView={view} collapsed={collapsed} onToggle={() => setCollapsed((current) => !current)} fresh={fresh} prototypeRooms={prototypeRooms} /><div className="working-surface">{selected ? <><ConversationHeader conversation={selected} surface={surface} onOverlay={setOverlay} />{surface === "hall" ? <HallSurface empty={isPrototypeConversation} /> : <ConversationSurface key={`${selected.slug}-${fresh}`} conversation={selected} persist={isPrototypeConversation} />}</> : <div className="desktop-welcome"><div className="welcome-orbit"><Image src="/brand/toskerlogo-icon-main.svg" alt="" width={120} height={120} priority /><span>✦</span><span>◌</span><span>⌁</span></div><p className="eyebrow">{dashboardLabel(prototypeUser)}</p><h2>{`Hey ${prototypeUser.displayName}, let's pick up where you left off`}</h2><p>Choose a conversation or Room from the left</p>{fresh ? <Link href="/personal/my-room" className="button button-primary">Open {dashboardLabel(prototypeUser)} <span>→</span></Link> : null}</div>}</div>{overlay && selected ? <OverlayPanel type={overlay} roomName={selected.name} onClose={() => setOverlay(null)} /> : null}</main>;
}
