import Image from "next/image";

export type ProductWorkspace = "explore" | "marketplace" | "studio" | "settings" | "help";
const exploreCards = [
  ["◒", "Quick Poll", "Popular now", "Ask the Room."], ["▦", "Kanban Board", "Popular now", "Organise lightly."], ["⌖", "Shared Map", "Popular now", "Plan together."], ["▧", "Photo Wall", "Popular now", "Collect it here."],
  ["▤", "Itinerary", "For trips", "Plan each day."], ["▣", "Packing List", "For trips", "Don’t forget it."], ["$", "Budget Tracker", "For trips", "Split the useful bits."], ["☁", "Weather", "For trips", "Check the forecast."],
  ["?", "Trivia Quiz", "For fun", "Test your knowledge."], ["◉", "Spin the Wheel", "For fun", "Make the decision."], ["♟", "Mini Games", "For fun", "Play together."], ["♫", "Music Player", "For fun", "Listen in sync."],
];
const marketCards = [
  ["skin", "Midnight Garden", "Room skin", "Mina Vale", "$2"], ["board", "Sprint Board", "Productivity", "North Star Co.", "Free"],
  ["game", "Pixel Arcade", "Game pack", "Ollie Makes", "$5"], ["trip", "Travel Wall", "Trip template", "Nomad Notes", "Free"],
  ["photo", "Polaroid Board", "Image board", "Soft Focus", "$2"], ["skin", "Sunday Paper", "Room skin", "Mina Vale", "$3"],
];

function ProductChrome({ children }: { current: ProductWorkspace; children: React.ReactNode }) {
  return <section className="product-canvas workspace-scroll">{children}</section>;
}

function Explore() { return <ProductChrome current="explore"><section className="explore-banner"><div><p className="eyebrow">Explore</p><h1>Make your Room more than chat.</h1><p>Find useful, social, and wonderfully specific things to add.</p><button disabled>Browse all</button></div><div className="art-reserve"><span>Future Tosker artwork</span></div></section><div className="filter-pills"><button className="active">Featured</button><button>Popular this week</button><button>For trips</button><button>For friends</button><button>For work</button><button>For fun</button></div><section className="surface-section compact-section"><div className="section-title"><div><p className="eyebrow">Browse ideas</p><h2>What does your Room need?</h2></div><span>Concept previews</span></div><div className="explore-grid">{exploreCards.map(([icon, title, category, body], index) => <article key={title} className={`explore-card card-${index + 1}`}><span>{icon}</span><div><small>{category}</small><h3>{title}</h3><p>{body}</p></div></article>)}</div></section></ProductChrome>; }
function Marketplace() { return <ProductChrome current="marketplace"><header className="surface-hero marketplace-hero"><p className="eyebrow">Marketplace</p><h1>Made for Rooms, by people with ideas</h1><p>A first look at the things creators could make for Tosker</p></header><section className="surface-section"><div className="section-title"><div><p className="eyebrow">Fresh finds</p><h2>From the future community</h2></div><div className="market-tabs"><button className="active">All</button><button>Skins</button><button>Apps</button><button>Games</button><button>Templates</button></div></div><div className="market-grid">{marketCards.map(([style, title, kind, creator, price]) => <article key={title} className="market-card"><div className={`market-art art-${style}`}><span>{title.slice(0, 1)}</span></div><div><small>{kind}</small><h3>{title}</h3><p>by {creator}</p><strong>{price}</strong></div></article>)}</div><p className="prototype-strip">Visual marketplace prototype · Nothing here can be purchased yet</p></section></ProductChrome>; }
function Studio() { return <ProductChrome current="studio"><header className="surface-hero studio-hero"><p className="eyebrow">Studio</p><h1>Make something people want in a Room</h1><p>For designers, developers, tinkerers, and people with one very specific idea</p><button className="button button-primary" disabled>Create something <span>＋</span></button></header><section className="surface-section studio-work"><div className="section-title"><div><p className="eyebrow">My creations</p><h2>Things taking shape</h2></div><span>Prototype data</span></div><div className="creation-list">{[["▤","Tokyo Itinerary Board","Template","Draft","—"],["◐","Neon Nights","Room skin","Published","$25"],["♟","Puzzle Rush","Mini game","Draft","—"],["▧","Photo Collage","Image board","Published","$74"]].map(([icon,name,type,status,earnings])=><article key={name}><span>{icon}</span><div><strong>{name}</strong><small>{type}</small></div><b className={status === "Published" ? "published" : ""}>{status}</b><i>{earnings}</i></article>)}</div><button className="studio-create" disabled>＋ Create something</button><div className="section-title creation-heading"><div><p className="eyebrow">Creation types</p><h2>Pick a starting point</h2></div></div><div className="creation-types">{[["◇","App","Useful"],["◐","Skin","Visual"],["▤","Template","A head start"],["♟","Game","Playful"]].map(([icon,title,body])=><button key={title} disabled><span>{icon}</span><strong>{title}</strong><small>{body}</small></button>)}</div></section></ProductChrome>; }
function Settings() { return <ProductChrome current="settings"><header className="surface-hero compact-hero"><p className="eyebrow">Settings</p><h1>Make Tosker yours.</h1><p>The controls are taking shape. These are visual settings only for now.</p></header><div className="settings-list">{[["Account","Name, profile, and the basics."],["Appearance","Roomy, compact, dark — eventually."],["Language","Preferred language: English"],["Notifications","Decide what earns your attention."],["Privacy","Clear choices, without a law degree."]].map(([title,body],i)=><button key={title} disabled><span>{["◎","◐","文","◉","◇"][i]}</span><div><strong>{title}</strong><small>{body}</small></div><i>→</i></button>)}</div><p className="prototype-strip">Prototype shell · Preferences do not save yet.</p></ProductChrome>; }
function Help() { return <ProductChrome current="help"><header className="surface-hero compact-hero"><p className="eyebrow">Help &amp; Feedback</p><h1>Tell us what feels odd.</h1><p>Or delightful. Especially delightful.</p></header><div className="help-grid">{[["✎","Send feedback","A thought, a feeling, a suspiciously specific opinion."],["!","Report a problem","Something broke. Let’s make it less broken."],["✦","Request a feature","What should Tosker learn to do next?"]].map(([icon,title,body])=><button key={title} disabled><span>{icon}</span><strong>{title}</strong><small>{body}</small><i>Prototype</i></button>)}</div><aside className="help-note"><Image src="/brand/toskerlogo-icon-main.svg" alt="" width={64} height={64}/><div><h2>Still finding our feet.</h2><p>This help surface will become useful as Tosker grows. For now, bring your notes to the founder walkthrough.</p></div></aside></ProductChrome>; }

export function ProductSurface({ surface }: { surface: ProductWorkspace }) { if (surface === "explore") return <Explore />; if (surface === "marketplace") return <Marketplace />; if (surface === "studio") return <Studio />; if (surface === "settings") return <Settings />; return <Help />; }
