"use client";
import Image from "next/image";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { members } from "@/data/mock-data";
import { AvatarStack } from "./avatar-stack";
const nav = [{ label: "Hall", href: "/realm/tokyo-2027", icon: "⌂" }, { label: "Chat", href: "/realm/tokyo-2027/chat", icon: "◌" }, { label: "Plan", href: "/realm/tokyo-2027/plan", icon: "◇" }, { label: "People", href: "/realm/tokyo-2027/people", icon: "◎" }];
function isActive(pathname: string, href: string) { return href === "/realm/tokyo-2027" ? pathname === href : pathname.startsWith(href); }
export function RealmShell({ children }: { children: React.ReactNode }) { const pathname = usePathname(); return <div className="realm-shell"><aside className="realm-sidebar"><Link href="/" className="realm-brand" aria-label="Back to Tosker home"><Image src="/brand/toskerlogo-icon-main.svg" alt="" width={48} height={48} priority /></Link><div className="realm-identity"><p className="eyebrow">Trip realm</p><h1>Tokyo 2027</h1><p>12–19 April 2027<br />Tokyo, Japan</p><div className="realm-members"><AvatarStack initials={members.slice(0, 4).map((member) => member.initials)} /><span>6 people</span></div></div><nav className="realm-nav" aria-label="Tokyo 2027 navigation">{nav.map((item) => <Link key={item.href} href={item.href} className={isActive(pathname, item.href) ? "active" : ""}><span aria-hidden="true">{item.icon}</span>{item.label}</Link>)}</nav><button className="add-something" type="button" disabled><span>＋</span><span>Add to Tosker<small>Coming later</small></span></button><Link className="leave-realm" href="/">← Your Toskers</Link></aside><div className="realm-stage"><header className="realm-mobile-header"><Link href="/" aria-label="Back to your Toskers">←</Link><div><strong>Tokyo 2027</strong><span>Tokyo, Japan · 6 people</span></div><span className="avatar avatar-gold">RY</span></header>{children}<nav className="mobile-realm-nav" aria-label="Tokyo 2027 mobile navigation">{nav.map((item) => <Link key={item.href} href={item.href} className={isActive(pathname, item.href) ? "active" : ""}><span aria-hidden="true">{item.icon}</span>{item.label}</Link>)}</nav></div></div>; }
