import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { and,eq,sql } from "drizzle-orm";
import type { ToskerDatabase } from "../../src/server/db/client";
import { users,profiles,roomMemberships,subrooms,subroomAccess,conversations,conversationParticipants,connections,tripPlans,tripPlaces,tripComments } from "../../src/server/db/schema";
import { readTrip,mutateTrip,readTripComments,TripError } from "../../src/server/trips/service";
import { AuthorizationDeniedError } from "../../src/server/auth/authorize";
import { recoverActiveRoute,type TripCommand } from "../../src/lib/trip-contract";
import { createQaFixture,cleanupQaFixture,resolveQaActors } from "./ms73-fixtures";

export async function verifyFp3Lifecycle(db:ToskerDatabase,concurrent=false){
 const {a,b,founder}=await resolveQaActors(db),f=await createQaFixture(db,"FP3 owned-card, Nuke, auth, Personal/Subroom regression");
 console.log("FP3 lifecycle fixture",JSON.stringify(f));
 const founderBefore=await db.select().from(profiles).where(eq(profiles.userId,founder.userId));
 const outsiders=(await db.select().from(users)).filter(u=>![a.userId,b.userId,founder.userId].includes(u.id));assert(outsiders.length);
 const outsider={userId:outsiders[0].id,authProvider:outsiders[0].authProvider,authSubject:outsiders[0].authSubject};
 const snap=()=>readTrip(db,a,f.slug);
 const change=async(command:TripCommand,actor=a,scope=f.slug,revision?:number)=>mutateTrip(db,actor,{roomSlug:scope,requestId:randomUUID(),expectedRevision:revision??(await readTrip(db,actor,scope)).revision,command});
 const pin=(name:string,i:number)=>({title:`QA ${name}`,latitude:1.28+i*.01,longitude:103.77+i*.02,source:"pin" as const,provider:null,providerId:null,address:"Synthetic public QA point, not a verified venue",attribution:"",license:""});
 await assert.rejects(()=>change({type:"add",candidate:pin("NUS",0),routeId:null}),TripError);
 assert.equal((await snap()).routes.length,0);
 await assert.rejects(()=>readTrip(db,outsider,f.slug),AuthorizationDeniedError);
 const r1=(await change({type:"create-route",name:"Route 1",color:"gold"})).resultId!,r2=(await change({type:"create-route",name:"Route 2",color:"sky"})).resultId!;
 const ids1:string[]=[],ids2:string[]=[];
 for(const [name,i] of [["NUS",0],["MBS",1],["Jewel",2]] as const)ids1.push((await change({type:"add",routeId:r1,candidate:pin(name,i)})).resultId!);
 for(const [name,i] of [["SIM",3],["NUS",0],["Jewel",2]] as const)ids2.push((await change({type:"add",routeId:r2,candidate:pin(name,i)},b)).resultId!);
 assert.equal(new Set([...ids1,...ids2]).size,6);assert.equal((await change({type:"add",routeId:r1,candidate:pin("NUS",0)})).resultId,ids1[0]);
 await change({type:"comment",placeId:ids1[0],body:"Route 1 discussion"});await change({type:"comment",placeId:ids2[1],body:"Route 2 discussion"},b);
 await change({type:"star-place",placeId:ids2[1],starred:true});await change({type:"edit-place",placeId:ids2[1],title:"QA NUS",note:"Only Route 2"});
 assert.equal((await snap()).places.find(p=>p.id===ids1[0])?.note,"");assert(!(await snap()).places.find(p=>p.id===ids1[0])?.starred);
 await change({type:"archive-place",placeId:ids2[1],archived:true});assert(!(await snap()).places.find(p=>p.id===ids1[0])?.archived);await change({type:"archive-place",placeId:ids2[1],archived:false});
 await change({type:"nuke-place",placeId:ids2[2]});assert((await snap()).places.some(p=>p.id===ids1[2]));
 assert.deepEqual((await snap()).memberships.filter(m=>m.routeId===r2).map(m=>m.position).sort(),[0,1]);
 await assert.rejects(()=>change({type:"stop",routeId:r1,placeId:ids2[1],isStop:false}));
 await assert.rejects(()=>change({type:"membership",routeId:r1,placeId:ids2[1],included:true}));
 await assert.rejects(()=>change({type:"order",routeId:r1,placeIds:[ids1[0],ids1[0]]}));
 const before=await snap(),r1Before=before.places.filter(p=>ids1.includes(p.id));
 const nuke={roomSlug:f.slug,requestId:randomUUID(),expectedRevision:before.revision,command:{type:"nuke-route" as const,routeId:r2}};
 await assert.rejects(()=>mutateTrip(db,outsider,nuke),AuthorizationDeniedError);
 await mutateTrip(db,b,nuke);assert((await mutateTrip(db,b,nuke)).replayed);
 await assert.rejects(()=>mutateTrip(db,b,{...nuke,command:{type:"nuke-route",routeId:r1}}),e=>e instanceof TripError&&e.code==="retry-mismatch");
 const after=await readTrip(db,founder,f.slug);assert.equal(after.routes.length,1);assert.deepEqual(after.places,r1Before);
 assert.equal((await readTripComments(db,b,f.slug,ids1[0])).comments.length,1);await assert.rejects(()=>readTripComments(db,b,f.slug,ids2[1]));
 await assert.rejects(()=>change({type:"add",routeId:r2,candidate:pin("No resurrection",3)}));
 await assert.rejects(()=>change({type:"edit-route",routeId:r2,name:"No resurrection",color:"sky"}));
 if(concurrent){const revision=after.revision;const race=await Promise.allSettled([change({type:"comment",placeId:ids1[0],body:"Before Nuke only"},a,f.slug,revision),change({type:"nuke-route",routeId:r1},b,f.slug,revision)]);assert.equal(race.filter(r=>r.status==="fulfilled").length,1);}
 if((await snap()).routes.some(r=>r.id===r1))await change({type:"nuke-route",routeId:r1});
 assert.equal((await snap()).places.length,0);assert.equal((await snap()).routes.length,0);
 const shape=(id:string)=>({id,name:id,color:"gold" as const,archived:false});
 assert.equal(recoverActiveRoute([shape("1"),shape("2"),shape("3")],[shape("1"),shape("3")],"2"),"3");assert.equal(recoverActiveRoute([shape("1"),shape("2")],[shape("1")],"2"),"1");assert.equal(recoverActiveRoute([shape("1")],[],"1"),null);
 const fresh=(await change({type:"create-route",name:"New explicit route",color:"rose"})).resultId!;
 const owned=(await change({type:"add",routeId:fresh,candidate:pin("Fresh",4)})).resultId!;
 await db.delete(roomMemberships).where(and(eq(roomMemberships.roomId,f.id),eq(roomMemberships.userId,b.userId)));
 await assert.rejects(()=>mutateTrip(db,b,nuke),AuthorizationDeniedError);await assert.rejects(()=>readTrip(db,b,f.slug),AuthorizationDeniedError);
 await db.insert(roomMemberships).values({roomId:f.id,userId:b.userId,role:"member"});
 console.log("PASS independent Route 1/2 cards, comments/notes/Star/archive/Card Nuke, Route Nuke/replay/stale/cross-route denial, last-route empty, recovery and revocation");
 // Owned selected Subroom: founder is explicitly included; other Rooms remain untouched.
 const [child]=await db.insert(subrooms).values({roomId:f.id,name:"FP3 selected QA",createdBy:a.userId,visibility:"selected",position:0}).returning();
 await db.insert(subroomAccess).values([a.userId,founder.userId].map(userId=>({subroomId:child.id,userId})));
 const [chat]=await db.insert(conversations).values({kind:"room",roomId:f.id,subroomId:child.id,isPrimary:false,title:child.name}).returning();
 await db.insert(conversationParticipants).values([a.userId,founder.userId].map(userId=>({conversationId:chat.id,userId})));
 const scope=`${f.slug}--${child.id}`;
 await assert.rejects(()=>readTrip(db,b,scope),AuthorizationDeniedError);
 const childRoute=(await change({type:"create-route",name:"Child route",color:"sage"},a,scope)).resultId!;
 const childCard=(await change({type:"add",routeId:childRoute,candidate:pin("Child",4)},a,scope)).resultId!;
 assert((await readTrip(db,founder,scope)).places.some(p=>p.id===childCard));
 await assert.rejects(()=>change({type:"nuke-place",placeId:owned},a,scope));await assert.rejects(()=>change({type:"nuke-route",routeId:childRoute}));
 await db.delete(subrooms).where(and(eq(subrooms.id,child.id),eq(subrooms.roomId,f.id),eq(subrooms.createdBy,a.userId)));
 assert.equal((await db.select().from(tripPlaces).where(eq(tripPlaces.id,childCard))).length,0);
 // Fresh server-only QA pair. Never modify retained Personal Chats or founder identity.
 const actors: typeof a[]=[];
 for(let i=0;i<2;i++){const subject=`fp3-${randomUUID()}`;const [u]=await db.insert(users).values({authProvider:"fp3-qa",authSubject:subject,tid:randomUUID().slice(0,7).toUpperCase()}).returning();await db.insert(profiles).values({userId:u.id,username:subject,displayName:`FP3 isolated ${i}`});actors.push({userId:u.id,authProvider:u.authProvider,authSubject:u.authSubject});}
 const pair=actors.map(a=>a.userId).sort().join(":"),[connection]=await db.insert(connections).values({requesterId:actors[0].userId,addresseeId:actors[1].userId,pairKey:pair,status:"accepted"}).returning();
 const [personal]=await db.insert(conversations).values({kind:"personal",directKey:pair,isPrimary:true}).returning();await db.insert(conversationParticipants).values(actors.map(a=>({conversationId:personal.id,userId:a.userId})));
 const personalScope=`personal--${personal.id}`,pr=(await change({type:"create-route",name:"Private QA",color:"iris"},actors[0],personalScope)).resultId!;
 const pp=(await change({type:"add",routeId:pr,candidate:pin("Personal",2)},actors[0],personalScope)).resultId!;
 await change({type:"comment",placeId:pp,body:"Pair only"},actors[1],personalScope);
 await assert.rejects(()=>readTripComments(db,founder,personalScope,pp),AuthorizationDeniedError);
 await db.update(connections).set({status:"pending"}).where(eq(connections.id,connection.id));await assert.rejects(()=>readTrip(db,actors[0],personalScope),AuthorizationDeniedError);
 await db.update(connections).set({status:"accepted"}).where(eq(connections.id,connection.id));
 await change({type:"nuke-route",routeId:pr},actors[1],personalScope);assert.equal((await db.select().from(tripComments).where(eq(tripComments.placeId,pp))).length,0);
 await db.delete(conversations).where(and(eq(conversations.id,personal.id),eq(conversations.directKey,pair)));
 for(const actor of actors)await db.delete(users).where(and(eq(users.id,actor.userId),eq(users.authSubject,actor.authSubject),eq(users.authProvider,"fp3-qa")));
 console.log("PASS Personal pair/relationship authorization, Subroom isolation/selected visibility, context/card/comment cascades");
 await cleanupQaFixture(db,f,true);
 assert.equal((await db.select().from(tripPlans).where(eq(tripPlans.roomId,f.id))).length,0);
 assert.deepEqual(await db.select().from(profiles).where(eq(profiles.userId,founder.userId)),founderBefore);
 await db.transaction(async tx=>{await tx.execute(sql`select set_config('tosker.trip_protocol','',true)`);await assert.rejects(()=>tx.transaction(t=>t.execute(sql`update trip_plans set revision=revision where id=(select id from trip_plans limit 1)`)));});
 console.log("PASS exact-owned cleanup, founder profile preserved, old-server write rejection");
}
