import assert from "node:assert/strict";
import { and, eq, sql } from "drizzle-orm";
import { getDatabase } from "../src/server/db/client";
import { users, rooms, roomMemberships, conversations, conversationParticipants, messages, messageMentions, notifications, subrooms, subroomAccess } from "../src/server/db/schema";
import { mentionSuggestions, validateMentionTargets } from "../src/server/conversations/mentions";
import { readMessageHistory } from "../src/server/conversations/history";
import { changeOwnMessage } from "../src/server/conversations/service";
import { adjustMentions, validMentionSpans } from "../src/lib/mentions";
import { parseChatDraft } from "../src/lib/chat-drafts";
const db = getDatabase(), roomId = crypto.randomUUID(), chatId = crypto.randomUUID(), childId = crypto.randomUUID(), childChatId = crypto.randomUUID();
const slug = `ms716-mentions-${roomId.slice(0,8)}`;
async function main() {
  const [a] = await db.select().from(users).where(eq(users.id,"0ee1e5a5-6d7a-4541-a6ca-ca69788997ef"));
  const [b] = await db.select().from(users).where(eq(users.id,"d7a58753-9877-45b2-9fc7-cca188559fed"));
  assert(a && b);
  const actor = (u: typeof a) => ({ userId:u.id, authProvider:u.authProvider, authSubject:u.authSubject });
  try {
    await db.insert(rooms).values({ id:roomId,slug,name:"MS716 mention acceptance",ownerId:a.id });
    await db.insert(roomMemberships).values([{ roomId,userId:a.id,role:"owner" },{ roomId,userId:b.id,role:"member" }]);
    await db.insert(subrooms).values({ id:childId,roomId,name:"Owners",visibility:"owners",createdBy:a.id });
    await db.insert(conversations).values([{id:chatId,roomId,kind:"room",isPrimary:true},{id:childChatId,roomId,subroomId:childId,kind:"room"}]);
    // Stale participant row deliberately must not grant suggestion/mention access.
    await db.insert(conversationParticipants).values([{conversationId:chatId,userId:a.id},{conversationId:chatId,userId:b.id},{conversationId:childChatId,userId:a.id},{conversationId:childChatId,userId:b.id}]);
    const members = await mentionSuggestions(db,actor(a),chatId,"");
    assert.equal(members.length,2); const target=members.find(m=>m.userId===b.id)!;
    const label=`@${target.username ?? target.name}`, body=`Hello ${label} — MS716`;
    const span={userId:b.id,start:6,length:label.length,label};
    assert(validMentionSpans(body,[span]));
    assert.deepEqual(adjustMentions(body,`X ${body}`,[span]),[{...span,start:8}]);
    assert.equal(adjustMentions(body,body.replace(label,"plain text"),[span]).length,0);
    assert(!validMentionSpans(body,[span,span]));
    assert.equal(parseChatDraft(JSON.stringify({body,mentions:[span],reply:null,pending:null,updatedAt:Date.now()})).mentions?.[0].userId,b.id);
    assert.equal((await validateMentionTargets(db,chatId,body,[span]))[0].userId,b.id);
    assert.equal((await mentionSuggestions(db,actor(a),childChatId,"")).length,1);
    await assert.rejects(()=>mentionSuggestions(db,actor(b),childChatId,""));
    await assert.rejects(()=>validateMentionTargets(db,childChatId,body,[span]));
    await db.update(subrooms).set({visibility:"selected"}).where(eq(subrooms.id,childId));
    await db.insert(subroomAccess).values({subroomId:childId,userId:a.id});
    assert.equal((await mentionSuggestions(db,actor(a),childChatId,"")).length,1);
    await assert.rejects(()=>mentionSuggestions(db,actor(b),childChatId,""));
    await db.insert(subroomAccess).values({subroomId:childId,userId:b.id});
    assert.equal((await mentionSuggestions(db,actor(b),childChatId,"")).length,2);
    assert.equal((await validateMentionTargets(db,childChatId,body,[span]))[0].userId,b.id);
    await db.delete(subroomAccess).where(and(eq(subroomAccess.subroomId,childId),eq(subroomAccess.userId,b.id)));
    await assert.rejects(()=>validateMentionTargets(db,childChatId,body,[span]));
    await db.update(subrooms).set({visibility:"everyone"}).where(eq(subrooms.id,childId));
    assert.equal((await mentionSuggestions(db,actor(b),childChatId,"")).length,2);
    await assert.rejects(()=>validateMentionTargets(db,chatId,"@Someone else",[{...span,start:0,length:13,label:"@Someone else"}]));
    const id=crypto.randomUUID(), replyId=crypto.randomUUID();
    await db.insert(messages).values([{id,conversationId:chatId,authorId:a.id,body},{id:replyId,conversationId:chatId,authorId:b.id,body:"MS716 reply",replyToId:id}]);
    await db.insert(messageMentions).values({...span,messageId:id});
    await db.insert(notifications).values({userId:b.id,actorId:a.id,conversationId:chatId,messageId:id,type:"message",isMention:true});
    let history=await readMessageHistory(db,actor(b),chatId);
    assert.equal(history.messages.find(m=>m.id===id)!.mentions[0].userId,b.id);
    assert(history.messages.find(m=>m.id===replyId)!.replyAuthor);
    await changeOwnMessage(db,actor(a),{conversationId:chatId,messageId:id,body:`X ${body}`});
    assert.equal((await readMessageHistory(db,actor(b),chatId)).messages.find(m=>m.id===id)!.mentions[0].start,8);
    assert.equal((await db.select({n:sql<number>`count(*)::int`}).from(notifications).where(eq(notifications.messageId,id)))[0].n,1);
    await changeOwnMessage(db,actor(a),{conversationId:chatId,messageId:id,remove:true});
    history=await readMessageHistory(db,actor(b),chatId);
    assert.equal(history.messages.find(m=>m.id===id)!.mentions.length,0);
    assert.equal(history.messages.find(m=>m.id===replyId)!.replyTo,"Message deleted");
    assert.equal((await db.select().from(notifications).where(eq(notifications.messageId,id)))[0].isMention,false);
    await db.delete(roomMemberships).where(and(eq(roomMemberships.roomId,roomId),eq(roomMemberships.userId,b.id)));
    await assert.rejects(()=>validateMentionTargets(db,chatId,body,[span]));
    console.log("PASS: bounded authorized mention suggestions; stale/private/removed/forged targets denied; explicit ID/span draft persistence; edit-shift/remove/tombstone; canonical reply author; no edit-notification duplication. Browser send/retry attention remains separate validation.");
  } finally { await db.delete(rooms).where(and(eq(rooms.id,roomId),eq(rooms.slug,slug))); }
}
main().then(()=>process.exit(0)).catch((error:unknown)=>{console.error("FAIL: mention acceptance",{location:error instanceof Error?error.stack?.match(/verify-mentions\.ts:\d+:\d+/)?.[0]:undefined});process.exit(1);});
