/** Rollback-only: no provider network, no retained fixtures, no founder mutations. */
import assert from "node:assert/strict";
import {randomUUID} from "node:crypto";
import {eq,and} from "drizzle-orm";
import {getDatabase,type ToskerDatabase} from "../src/server/db/client";
import {conversations,roomMemberships,subrooms,conversationParticipants} from "../src/server/db/schema";
import {createQaFixture,resolveQaActors} from "./lib/ms73-fixtures";
import {mutateTrip,readTrip} from "../src/server/trips/service";
import {sendMapPing,PingRateError} from "../src/server/maps/pings";
import {getRealtimeServer} from "../src/server/realtime/provider";
import {conversationChannel} from "../src/lib/realtime-contract";
import {PING_TTL,validPing,pingPlacement} from "../src/lib/maps/ping-contract";
import {roadKey,supportedRoadPoints} from "../src/lib/maps/road-contract";
import {privateOriginPoint,ORIGIN_CONSENT} from "../src/lib/maps/private-origin";
import {credibleNearby} from "../src/lib/maps/nearby-place";
import {legMidpoint} from "../src/lib/maps/leg-labels";
import {routingPlaces} from "../src/lib/trip-contract";
const db=getDatabase(),rollback=new Error("FP6 rollback");
async function main(){
  const origin={latitude:1.2837,longitude:103.8607};
  assert(!privateOriginPoint(origin));assert(privateOriginPoint({...origin,consent:ORIGIN_CONSENT}));
  assert(!privateOriginPoint({...origin,latitude:40,consent:ORIGIN_CONSENT}));
  assert(supportedRoadPoints([{id:"sg",...origin},{id:"jb",latitude:1.46,longitude:103.76}]));
  const known={name:"Known cafe",result_type:"amenity",lat:origin.latitude+0.0001,lon:origin.longitude};
  assert(credibleNearby(known,origin));assert(!credibleNearby({...known,lat:origin.latitude+0.001},origin));
  assert(!credibleNearby({...known,result_type:"street"},origin));assert(!credibleNearby({...known,name:""},origin));
  assert(credibleNearby({...known,name:"Second cafe",lon:origin.longitude+0.00001},origin));
  assert.deepEqual(legMidpoint([[103.8,1.3],[103.82,1.3]]),[103.81,1.3]);
  const placement={id:randomUUID(),kind:"attention",...origin};assert(pingPlacement(placement));assert(!pingPlacement({...placement,kind:"toString"}));
  const ping={...placement,senderId:randomUUID(),senderName:"QA",expiresAt:Date.now()+PING_TTL};assert.equal(validPing(ping),true);assert.equal(validPing(ping,Date.now()+PING_TTL+1),false);assert.equal(validPing({...ping,expiresAt:Date.now()+60000}),false);
  const realtime=getRealtimeServer(),original=realtime.channels.get.bind(realtime.channels),published:{channel:string;message:unknown}[]=[];
  realtime.channels.get=((channel:string)=>({publish:async(message:unknown)=>{published.push({channel,message});}})) as unknown as typeof realtime.channels.get;
  try{await db.transaction(async tx=>{
    const d=tx as unknown as ToskerDatabase,{a,b,founder}=await resolveQaActors(tx),f=await createQaFixture(d,"FP6 addendum rollback authorization and reorder audit");
    const read=()=>readTrip(d,a,f.slug);
    const change=async(command:Parameters<typeof mutateTrip>[2]["command"])=>{const state=await read();return mutateTrip(d,a,{roomSlug:f.slug,expectedRevision:state.revision,requestId:randomUUID(),command});};
    const candidate={title:"QA MBS",source:"search" as const,provider:"qa",providerId:"qa-mbs",...origin,address:"QA",attribution:"QA",license:"QA"};
    const poi=await change({type:"add",routeId:null,candidate}),routeId=(await read()).routes[0].id;
    const manual=await change({type:"add",routeId,candidate:{...candidate,title:"Checkpoint",source:"pin",provider:null,providerId:null,latitude:1.29}});
    const ids=[poi.resultId!,manual.resultId!];
    await assert.rejects(()=>change({type:"order",routeId,placeIds:[...ids].reverse()}));
    await change({type:"lock-position",routeId,position:0,locked:false});
    const before=roadKey(routingPlaces(await read(),routeId),"drive");
    await change({type:"order",routeId,placeIds:[...ids].reverse()});
    assert.notEqual(roadKey(routingPlaces(await read(),routeId),"drive"),before);
    assert.deepEqual(routingPlaces(await read(),routeId).map(p=>p.id),[...ids].reverse());
    await assert.rejects(()=>change({type:"move-checkpoint",placeId:ids[0],latitude:1.3,longitude:103.85}));
    const beforeMove=roadKey(routingPlaces(await read(),routeId),"drive");
    await change({type:"move-checkpoint",placeId:ids[1],latitude:1.291,longitude:103.854});
    assert.notEqual(roadKey(routingPlaces(await read(),routeId),"drive"),beforeMove);
    const stale=(await read()).revision;
    await change({type:"order",routeId,placeIds:ids});
    await assert.rejects(()=>mutateTrip(d,b,{roomSlug:f.slug,expectedRevision:stale,requestId:randomUUID(),command:{type:"order",routeId,placeIds:[...ids].reverse()}}));
    await change({type:"skip-place",placeId:ids[1],skipped:true});assert.equal(routingPlaces(await read(),routeId).length,1);
    assert.deepEqual(await readTrip(d,b,f.slug),await readTrip(d,founder,f.slug));
    const sent=await sendMapPing(d,a,f.slug,placement);assert.equal(sent.senderId,a.userId);assert(validPing(sent));
    assert.equal(published[0].channel,conversationChannel(f.conversationId));assert.deepEqual((published[0].message as {extras:unknown}).extras,{ephemeral:true});
    const [sandbox]=await tx.select().from(conversations).where(and(eq(conversations.kind,"sandbox"),eq(conversations.ownerId,a.userId)));
    await assert.rejects(()=>sendMapPing(d,a,`sandbox--${sandbox.id}`,placement));
    const [sub]=await tx.insert(subrooms).values({roomId:f.id,name:"FP6 private QA",createdBy:a.userId,visibility:"owners"}).returning();
    const [chat]=await tx.insert(conversations).values({kind:"room",roomId:f.id,subroomId:sub.id,title:"FP6 private QA"}).returning();
    await tx.insert(conversationParticipants).values({conversationId:chat.id,userId:a.userId});
    await assert.rejects(()=>sendMapPing(d,b,`${f.slug}--${sub.id}`,placement));
    await sendMapPing(d,a,`${f.slug}--${sub.id}`,{...placement,id:randomUUID()});
    await tx.delete(roomMemberships).where(and(eq(roomMemberships.roomId,f.id),eq(roomMemberships.userId,b.userId)));
    const count=published.length;await assert.rejects(()=>sendMapPing(d,b,f.slug,placement));assert.equal(published.length,count);
    for(let i=0;i<4;i++)await sendMapPing(d,a,f.slug,{...placement,id:randomUUID()});
    await assert.rejects(()=>sendMapPing(d,a,f.slug,{...placement,id:randomUUID()}),PingRateError);
    throw rollback;
  });}catch(e){if(e!==rollback)throw e;}finally{realtime.channels.get=original;}
  console.log("PASS FP6 consent/region/nearby20m/densePOI/expiry/leg midpoint; POI/manual order, locks, stale revision, move/Skip invalidation; Room/Subroom/revoked/Sandbox ping auth, canonical sender, ephemeral publish and rate limit. All DB changes rolled back, no provider calls.");
}
main().catch(e=>{console.error({failure:"FP6 addendum",kind:e?.name,assertion:e instanceof assert.AssertionError?e.message.split("\n")[0]:undefined});process.exitCode=1;}).finally(()=>db.$client.end());
