import assert from "node:assert/strict";
import { and, eq, sql } from "drizzle-orm";
import { getDatabase } from "../src/server/db/client";
import { users, profiles, rooms, roomMemberships, conversations, conversationParticipants, invites, notifications, connections } from "../src/server/db/schema";
import { invitationCandidates, invitationManagement, sendDirectInvitations, respondToInvitation, generateShareInvitation, cancelInvitation, inviteLimit } from "../src/server/rooms/invitation-service";
import { joinRoomInvite, withdrawRoomMember } from "../src/server/rooms/lifecycle";
import { encryptInvite, decryptInvite, inviteHash, inviteToken } from "../src/server/rooms/invite-crypto";
import { hallScope } from "../src/server/hall/service";
import { issueConversationToken } from "../src/server/realtime/auth";

const db = getDatabase();
const roomId = crypto.randomUUID(), conversationId = crypto.randomUUID();
async function main() {
  const ids = Array.from({ length: 4 }, () => crypto.randomUUID());
  const [a, b, c, d] = ids.map((userId) => ({ userId, authProvider: "fp2-qa", authSubject: userId }));
  // Exact owned fixtures retained for FP2 acceptance/cleanup, never existing identities.
  console.log("FP2 service fixture", JSON.stringify({ roomId, conversationId, userIds: ids }));
  await db.insert(users).values(ids.map((id) => ({ id, tid: `fp2-${id}`, authProvider: "fp2-qa", authSubject: id })));
  await db.insert(profiles).values(ids.map((id, i) => ({ userId: id, displayName: `FP2 service ${i}`, username: `fp2_${id.slice(0, 8)}` })));
  await db.insert(rooms).values({ id: roomId, slug: `fp2-service-${roomId}`, name: "FP2 invitation service QA", ownerId: a.userId });
  await db.insert(roomMemberships).values({ roomId, userId: a.userId, role: "owner" });
  await db.insert(conversations).values({ id: conversationId, roomId, kind: "room", isPrimary: true });
  await db.insert(conversationParticipants).values({ conversationId, userId: a.userId });
  await db.insert(connections).values({ requesterId: a.userId, addresseeId: b.userId, pairKey: [a.userId, b.userId].sort().join(":"), status: "accepted" });
  const token = inviteToken(), encrypted = encryptInvite(token, roomId, conversationId);
  assert.equal(decryptInvite(encrypted, roomId, conversationId), token);
  assert.ok(!encrypted.includes(token));
  assert.throws(() => decryptInvite(encrypted, roomId, a.userId));
  assert.throws(() => decryptInvite(encrypted.slice(0, -3) + "xxx", roomId, conversationId));
  const candidates = await invitationCandidates(db, a, roomId, "", "friends");
  assert.deepEqual(candidates.map((row) => row.userId), [b.userId]);
  assert.equal((await invitationCandidates(db, a, roomId, `fp2_${c.userId.slice(0, 8)}`, "username")).length, 1);
  assert.equal((await invitationCandidates(db, a, roomId, "fp2_", "username")).length, 0);
  await assert.rejects(() => invitationCandidates(db, c, roomId, "", "friends"));
  const input = { roomId, mode: "friends" as const, userIds: [b.userId] };
  await assert.rejects(() => sendDirectInvitations(db, c, input));
  await assert.rejects(() => sendDirectInvitations(db, a, { ...input, userIds: [c.userId] }));
  const [first, duplicate] = await Promise.all([sendDirectInvitations(db, a, input), sendDirectInvitations(db, a, input)]);
  const invitationId = first[0].invitationId!;
  assert.equal(invitationId, duplicate[0].invitationId);
  assert.equal((await db.select().from(notifications).where(eq(notifications.invitationId, invitationId))).length, 1);
  await assert.rejects(() => hallScope(db, b, conversationId));
  await assert.rejects(() => issueConversationToken(db, b, conversationId));
  await assert.rejects(() => respondToInvitation(db, c, invitationId, true));
  await assert.rejects(() => cancelInvitation(db, c, roomId, invitationId));
  await Promise.all([respondToInvitation(db, b, invitationId, true), respondToInvitation(db, b, invitationId, true)]);
  await hallScope(db, b, conversationId);
  assert.equal((await db.select().from(roomMemberships).where(and(eq(roomMemberships.roomId, roomId), eq(roomMemberships.userId, b.userId)))).length, 1);
  assert.equal((await sendDirectInvitations(db, a, input))[0].state, "member");
  await assert.rejects(() => generateShareInvitation(db, b, roomId, 24));
  const directC = await sendDirectInvitations(db, b, { roomId, mode: "username", username: `@fp2_${c.userId.slice(0, 8)}` });
  await respondToInvitation(db, c, directC[0].invitationId!, false);
  await assert.rejects(() => respondToInvitation(db, c, directC[0].invitationId!, true));
  const cancelled = await sendDirectInvitations(db, b, { roomId, mode: "username", username: `fp2_${c.userId.slice(0, 8)}` });
  await cancelInvitation(db, a, roomId, cancelled[0].invitationId!);
  await assert.rejects(() => respondToInvitation(db, c, cancelled[0].invitationId!, true));
  const pendingC = await sendDirectInvitations(db, b, { roomId, mode: "username", username: `fp2_${c.userId.slice(0, 8)}` });
  const legacy = inviteToken();
  await db.insert(invites).values({ roomId, inviterId: a.userId, tokenHash: inviteHash(legacy), expiresAt: new Date(Date.now() + 3600000) });
  const [x, y] = await Promise.all([generateShareInvitation(db, a, roomId, 1), generateShareInvitation(db, a, roomId, 168)]);
  const active = (await invitationManagement(db, a, roomId)).share!;
  assert.ok(active.id === x.id || active.id === y.id);
  assert.equal((await invitationManagement(db, a, roomId)).share?.token, active.token);
  assert.equal((await invitationManagement(db, b, roomId)).share, null);
  const old = active.id === x.id ? y : x;
  await assert.rejects(() => joinRoomInvite(db, c, old.token));
  await assert.rejects(() => joinRoomInvite(db, c, legacy));
  assert.equal((await db.select().from(invites).where(eq(invites.id, pendingC[0].invitationId!)))[0].status, "pending");
  await assert.rejects(() => cancelInvitation(db, b, roomId, active.id));
  await Promise.all([joinRoomInvite(db, c, active.token), joinRoomInvite(db, d, active.token)]);
  await cancelInvitation(db, a, roomId, active.id);
  await assert.rejects(() => joinRoomInvite(db, c, active.token));
  await hallScope(db, c, conversationId); await hallScope(db, d, conversationId);
  assert.equal((await invitationManagement(db, a, roomId)).share, null);
  const expired = await generateShareInvitation(db, a, roomId, 24);
  await db.update(invites).set({ expiresAt: new Date(Date.now() - 1000) }).where(eq(invites.id, expired.id));
  await assert.rejects(() => joinRoomInvite(db, c, expired.token));
  assert.equal((await invitationManagement(db, a, roomId)).share, null);
  await assert.rejects(() => generateShareInvitation(db, a, roomId, 0));
  // Forced rollback establishes removal failure does not grant new invitation authority.
  await assert.rejects(() => withdrawRoomMember(db, a, roomId, a.userId));
  await withdrawRoomMember(db, a, roomId, b.userId, async () => {});
  await assert.rejects(() => sendDirectInvitations(db, b, input));
  await assert.rejects(() => respondToInvitation(db, c, pendingC[0].invitationId!, true));
  const quota = await Promise.allSettled(Array.from({ length: 35 }, () => inviteLimit(db, d, "lookup")));
  assert.equal(quota.filter((row) => row.status === "fulfilled").length, 30);
  assert.equal(quota.filter((row) => row.status === "rejected").length, 5);
  const invariants = await db.execute(sql`select count(*)::int as failures from (select room_id from invites where kind='share' and status='pending' group by room_id having count(*) > 1) invalid`);
  assert.equal(invariants.rows[0].failures, 0);
  console.log("PASS FP2 invitations: encryption/AAD/tamper, scoped exact discovery, consent/no pending access or token, duplicate delivery, recipient mismatch, decline/cancel, reusable share/concurrent generation/recovery/expiry/revoke/legacy transition, membership retained, removal and atomic limits.");
}
main().then(() => process.exit(0)).catch((error: unknown) => { console.error("FAIL FP2 invitations", { location: error instanceof Error ? error.stack?.match(/verify-fp2-invitations\.ts:\d+:\d+/)?.[0] : undefined, type: error instanceof Error ? error.name : "unknown" }); process.exit(1); });
