import assert from "node:assert/strict";
import { eq } from "drizzle-orm";
import { getDatabase } from "../src/server/db/client";
import { conversations, conversationParticipants, hallCommentReactions, hallItems, messageReactions, messages, notifications, profiles, roomMemberships, rooms, roomTags, subrooms, users } from "../src/server/db/schema";
import { changeOwnMessage, setMessageReaction } from "../src/server/conversations/service";
import { addHallComment, editHallNote, hallScope, listHallComments, moveHallItem, setCommentReaction } from "../src/server/hall/service";
import { normalizeRoomTags } from "../src/lib/room-tags";

const db = getDatabase();
const roomId = crypto.randomUUID(), conversationId = crypto.randomUUID(), childConversationId = crypto.randomUUID(), childId = crypto.randomUUID();
const messageId = crypto.randomUUID(), itemId = crypto.randomUUID(), otherItemId = crypto.randomUUID(), commentId = crypto.randomUUID();
async function main() {
  const candidates = await db.select({ user: users, name: profiles.displayName }).from(users).innerJoin(profiles, eq(users.id, profiles.userId));
  const aUser = candidates.find(({ name }) => name.includes("tosker.user.a"))?.user;
  const bUser = candidates.find(({ name }) => name.includes("tosker.user.b"))?.user;
  const outsiderUser = candidates.find(({ user }) => user.id !== aUser?.id && user.id !== bUser?.id)?.user;
  assert(aUser && bUser && outsiderUser, "Two existing isolated test users and outsider required");
  const actor = (user: typeof users.$inferSelect) => ({ userId: user.id, authProvider: user.authProvider, authSubject: user.authSubject });
  const a = actor(aUser), b = actor(bUser), outsider = actor(outsiderUser);
  const notificationCount = (await db.select({ id: notifications.id }).from(notifications)).length;
  try {
    await db.insert(rooms).values({ id: roomId, ownerId: a.userId, slug: `qa-ms6a-${roomId}`, name: "Temporary MS6A verification" });
    await db.insert(roomMemberships).values([{ roomId, userId: a.userId, role: "owner" }, { roomId, userId: b.userId, role: "member" }]);
    await db.insert(subrooms).values({ id: childId, roomId, name: "Owner only", visibility: "owners", createdBy: a.userId });
    await db.insert(conversations).values([{ id: conversationId, roomId, kind: "room", isPrimary: true }, { id: childConversationId, roomId, subroomId: childId, kind: "room" }]);
    await db.insert(conversationParticipants).values([{ conversationId, userId: a.userId }, { conversationId, userId: b.userId }, { conversationId: childConversationId, userId: a.userId }]);
    const tags = normalizeRoomTags(["Just Chilling", "  Night   Owls ", "night owls"]);
    assert.deepEqual(tags, ["Just Chilling", "Night Owls"]);
    await db.insert(roomTags).values(tags.map((value) => ({ roomId, value })));
    assert.equal((await db.select().from(roomTags).where(eq(roomTags.roomId, roomId))).length, 2);
    assert.throws(() => normalizeRoomTags(["x".repeat(25)]));
    assert.throws(() => normalizeRoomTags(["a", "b", "c", "d", "e", "f"]));
    await db.insert(messages).values({ id: messageId, conversationId, authorId: a.userId, body: "Original" });
    const reaction = { conversationId, messageId, emoji: "👍🏽", active: true };
    await Promise.all([setMessageReaction(db, a, reaction), setMessageReaction(db, a, reaction)]);
    await setMessageReaction(db, b, reaction);
    let values = await db.select().from(messageReactions).where(eq(messageReactions.messageId, messageId));
    assert.equal(values.length, 2);
    await setMessageReaction(db, b, { ...reaction, active: false });
    values = await db.select().from(messageReactions).where(eq(messageReactions.messageId, messageId));
    assert.equal(values.length, 1); assert.equal(values[0].userId, a.userId);
    await assert.rejects(() => setMessageReaction(db, outsider, reaction));
    await assert.rejects(() => setMessageReaction(db, b, { ...reaction, conversationId: childConversationId }));
    await assert.rejects(() => setMessageReaction(db, a, { ...reaction, emoji: "not emoji" }));
    await assert.rejects(() => changeOwnMessage(db, b, { conversationId, messageId, body: "Forged" }));
    await assert.rejects(() => changeOwnMessage(db, b, { conversationId, messageId, remove: true }));
    await changeOwnMessage(db, a, { conversationId, messageId, body: "Edited" });
    let [message] = await db.select().from(messages).where(eq(messages.id, messageId));
    assert.equal(message.body, "Edited"); assert(message.editedAt);
    await db.insert(hallItems).values([{ id: itemId, roomId, conversationId, authorId: a.userId, kind: "note", title: "Original", body: "Body" }, { id: otherItemId, roomId, conversationId, authorId: a.userId, kind: "note", title: "Second", body: "Body" }]);
    await editHallNote(db, a, { conversationId, itemId, title: "Updated", body: "Updated body" });
    await assert.rejects(() => editHallNote(db, b, { conversationId, itemId, title: "Forged", body: "No" }));
    await assert.rejects(() => editHallNote(db, a, { conversationId: childConversationId, itemId, title: "Cross-scope", body: "No" }));
    const comment = { conversationId, itemId, id: commentId, body: "A's comment" };
    await addHallComment(db, a, comment); await addHallComment(db, a, comment);
    const commentReaction = { conversationId, itemId, commentId, emoji: "🎉", active: true };
    await Promise.all([setCommentReaction(db, a, commentReaction), setCommentReaction(db, a, commentReaction)]);
    await setCommentReaction(db, b, commentReaction);
    let page = await listHallComments(db, b, conversationId, itemId);
    assert.equal(page.comments.length, 1); assert.equal(page.comments[0].reactions[0].count, 2); assert.equal(page.comments[0].reactions[0].mine, true);
    await setCommentReaction(db, b, { ...commentReaction, active: false });
    page = await listHallComments(db, b, conversationId, itemId);
    assert.equal(page.comments[0].reactions[0].count, 1); assert.equal(page.comments[0].reactions[0].mine, false);
    await assert.rejects(() => setCommentReaction(db, b, { ...commentReaction, itemId: otherItemId }));
    await assert.rejects(() => setCommentReaction(db, outsider, commentReaction));
    await assert.rejects(() => hallScope(db, b, childConversationId));
    const childScope = await hallScope(db, a, childConversationId);
    assert.equal((await db.select().from(hallItems).where(childScope)).length, 0);
    await moveHallItem(db, a, { conversationId, itemId, targetId: otherItemId });
    const [moved] = await db.select().from(hallItems).where(eq(hallItems.id, itemId));
    assert.equal(moved.position, 1);
    await changeOwnMessage(db, a, { conversationId, messageId, remove: true });
    await changeOwnMessage(db, a, { conversationId, messageId, remove: true });
    [message] = await db.select().from(messages).where(eq(messages.id, messageId));
    assert.equal(message.body, ""); assert(message.deletedAt);
    assert.equal((await db.select().from(messageReactions).where(eq(messageReactions.messageId, messageId))).length, 0);
    await assert.rejects(() => setMessageReaction(db, a, reaction));
    await assert.rejects(() => changeOwnMessage(db, a, { conversationId, messageId, body: "Restore" }));
    assert.equal((await db.select({ id: notifications.id }).from(notifications)).length, notificationCount, "Metadata actions do not create notifications");
    await db.delete(hallItems).where(eq(hallItems.id, itemId));
    assert.equal((await db.select().from(hallCommentReactions).where(eq(hallCommentReactions.commentId, commentId))).length, 0);
    console.log(JSON.stringify({ ms6a: "PASS", twoUsers: true, reactionStack: true, idempotence: true, ownerOnlyEditDelete: true, tombstoneClearsBody: true, hallAuthorEdit: true, commentReactions: true, targetScopeDenied: true, ownersSubroomDenied: true, customTags: true, deterministicReorder: true, metadataNoNotifications: true, cascadeCleanup: true }));
  } finally {
    await db.delete(hallItems).where(eq(hallItems.roomId, roomId));
    await db.delete(rooms).where(eq(rooms.id, roomId));
  }
}
main().then(() => process.exit(0)).catch((error) => { console.error(error); process.exit(1); });
