import assert from "node:assert/strict";
import { acknowledgeDraft, chatDraftKey, createChatDraftStore, EMPTY_CHAT_DRAFT, parseChatDraft } from "../src/lib/chat-drafts";

const records = new Map<string, string>();
const storage = { getItem: (key: string) => records.get(key) ?? null, setItem: (key: string, value: string) => { records.set(key, value); }, removeItem: (key: string) => { records.delete(key); } };
const a = chatDraftKey("a", "room");
const b = chatDraftKey("b", "room");
const other = chatDraftKey("a", "personal");
const store = createChatDraftStore(() => storage);
const id = "55cc8792-1d0a-4106-82b6-ff5736e8c761";
const reply = { id: "original", body: "source", author: "A" };
store.update(a, (current) => ({ ...current, body: "  this should survive  ", reply, pending: { id, body: "this should survive", replyToId: reply.id } }));
assert.equal(store.get(b), EMPTY_CHAT_DRAFT, "Other actor cannot inherit draft");
assert.equal(store.get(other), EMPTY_CHAT_DRAFT, "Other conversation cannot inherit draft");
const restored = createChatDraftStore(() => storage);
assert.deepEqual(restored.get(a), store.get(a), "Reload preserves text, reply and idempotency key");
assert.equal(acknowledgeDraft(store.get(a), "unrelated"), store.get(a));
restored.update(a, (current) => ({ ...current, body: "new typing" }));
restored.update(a, (current) => acknowledgeDraft(current, id));
assert.equal(restored.get(a).body, "new typing", "Late ack cannot erase new text");
assert.equal(restored.get(a).reply?.id, reply.id);
assert.equal(restored.get(a).pending, null);
store.update(a, (current) => acknowledgeDraft(current, id));
assert.equal(store.get(a).body, "");
assert.equal(store.get(a).reply, null);
assert.equal(records.has(a), false, "Confirmed unchanged draft removed from session storage");
for (const raw of ["broken", "null", "{}", JSON.stringify({ ...EMPTY_CHAT_DRAFT, updatedAt: Date.now() - 86400001 }), JSON.stringify({ ...EMPTY_CHAT_DRAFT, body: "x".repeat(8001), updatedAt: Date.now() })]) assert.equal(parseChatDraft(raw), EMPTY_CHAT_DRAFT);
const unavailable = createChatDraftStore(() => { throw new Error("blocked storage"); });
unavailable.update(a, (current) => ({ ...current, body: "memory fallback" }));
assert.equal(unavailable.get(a).body, "memory fallback");
const demo = chatDraftKey(undefined, "room");
store.update(demo, (current) => ({ ...current, body: "demo" }));
assert.equal(records.has(demo), false, "Demo never persists authenticated draft state");
console.log("PASS: draft reload/navigation model, actor/conversation isolation, stable retry ID, late ACK, invalid/expired data and disabled-storage fallback.");
