import assert from "node:assert/strict";
import { createHash, randomBytes } from "node:crypto";
import { and, eq } from "drizzle-orm";
import { Realtime } from "ably";
import { getDatabase } from "../src/server/db/client";
import { users, rooms, roomMemberships, roomTags, invites, subrooms, subroomAccess, conversations, conversationParticipants, messages } from "../src/server/db/schema";
import { joinRoomInvite, revokeRoomInvite, updateRoom, withdrawRoomMember } from "../src/server/rooms/lifecycle";
import { hallScope } from "../src/server/hall/service";
import { changeOwnMessage } from "../src/server/conversations/service";
import { issueConversationToken } from "../src/server/realtime/auth";
import { revokeActorRealtime } from "../src/server/realtime/provider";
import { conversationChannel } from "../src/lib/realtime-contract";

const db = getDatabase(), roomId = crypto.randomUUID(), chatId = crypto.randomUUID(), childId = crypto.randomUUID(), childChatId = crypto.randomUUID(), messageId = crypto.randomUUID();
const slug = `qa-ms712-${roomId}`;
const clients: Realtime[] = [];
async function main() {
  const [aUser] = await db.select().from(users).where(eq(users.id, "0ee1e5a5-6d7a-4541-a6ca-ca69788997ef"));
  const [bUser] = await db.select().from(users).where(eq(users.id, "d7a58753-9877-45b2-9fc7-cca188559fed"));
  assert.ok(aUser && bUser);
  const actor = (user: typeof aUser) => ({ userId: user.id, authProvider: user.authProvider, authSubject: user.authSubject });
  const a = actor(aUser), b = actor(bUser), outsider = { ...b, userId: crypto.randomUUID() };
  const member = () => db.select().from(roomMemberships).where(and(eq(roomMemberships.roomId, roomId), eq(roomMemberships.userId, b.userId)));
  const makeInvite = async () => {
    const token = randomBytes(32).toString("base64url"), id = crypto.randomUUID();
    await db.insert(invites).values({ id, roomId, inviterId: a.userId, tokenHash: createHash("sha256").update(token).digest("hex"), expiresAt: new Date(Date.now() + 3600000) });
    return { id, token };
  };
  try {
    await db.insert(rooms).values({ id: roomId, slug, name: "Temporary MS7.1.2 lifecycle acceptance", ownerId: a.userId });
    await db.insert(roomMemberships).values({ roomId, userId: a.userId, role: "owner" });
    await db.insert(subrooms).values({ id: childId, roomId, name: "Public child", visibility: "everyone", createdBy: a.userId });
    await db.insert(conversations).values([{ id: chatId, roomId, kind: "room", isPrimary: true }, { id: childChatId, roomId, subroomId: childId, kind: "room" }]);
    await db.insert(conversationParticipants).values([{ conversationId: chatId, userId: a.userId }, { conversationId: childChatId, userId: a.userId }]);
    const accepted = await makeInvite();
    await Promise.all([joinRoomInvite(db, b, accepted.token), joinRoomInvite(db, b, accepted.token)]);
    assert.equal((await member()).length, 1);
    await hallScope(db, b, childChatId);
    await db.insert(messages).values({ id: messageId, conversationId: chatId, authorId: b.userId, body: "Historical B message retained" });
    await assert.rejects(() => updateRoom(db, b, { roomId, name: "Forged", tags: [] }));
    await updateRoom(db, a, { roomId, name: "Updated QA Room", tags: ["Just Chilling", "Travel", "Osaka"] });
    assert.equal((await db.select().from(rooms).where(eq(rooms.id, roomId)))[0].name, "Updated QA Room");
    assert.equal((await db.select().from(roomTags).where(eq(roomTags.roomId, roomId))).length, 3);
    await assert.rejects(() => withdrawRoomMember(db, a, roomId, a.userId));
    await assert.rejects(() => withdrawRoomMember(db, b, roomId, a.userId));
    await assert.rejects(() => withdrawRoomMember(db, outsider, roomId, b.userId));
    const revoked = await makeInvite();
    await assert.rejects(() => revokeRoomInvite(db, b, roomId, revoked.id));
    await revokeRoomInvite(db, a, roomId, revoked.id);
    await assert.rejects(() => joinRoomInvite(db, b, revoked.token));
    await assert.rejects(() => withdrawRoomMember(db, a, roomId, b.userId, async () => { throw new Error("Simulated provider outage"); }));
    assert.equal((await member()).length, 1, "Failed provider revoke rolls back removal");
    await hallScope(db, b, childChatId);
    assert.equal((await db.select().from(invites).where(eq(invites.id, accepted.id)))[0].status, "accepted");
    const oldToken = await issueConversationToken(db, b, chatId);
    let entered!: () => void, release!: () => void;
    const atProvider = new Promise<void>((resolve) => { entered = resolve; });
    const gate = new Promise<void>((resolve) => { release = resolve; });
    const withdrawal = withdrawRoomMember(db, a, roomId, b.userId, async (id) => { entered(); await gate; await revokeActorRealtime(id); });
    await atProvider;
    let tokenSettled = false;
    const renewal = issueConversationToken(db, b, chatId).then(() => { tokenSettled = true; return true; }, () => { tokenSettled = true; return false; });
    await new Promise((resolve) => setTimeout(resolve, 150));
    assert.equal(tokenSettled, false, "Concurrent token issuance waits for withdrawal");
    release(); await withdrawal;
    assert.equal(await renewal, false, "Waiting token issuance rechecks committed authorization");
    assert.equal((await member()).length, 0);
    await assert.rejects(() => hallScope(db, b, chatId));
    await assert.rejects(() => hallScope(db, b, childChatId));
    await assert.rejects(() => changeOwnMessage(db, b, { conversationId: chatId, messageId, body: "After removal" }));
    await assert.rejects(() => joinRoomInvite(db, b, accepted.token));
    const [historical] = await db.select().from(messages).where(eq(messages.id, messageId));
    assert.equal(historical.authorId, b.userId); assert.equal(historical.body, "Historical B message retained");
    assert.equal((await db.select().from(subroomAccess).where(and(eq(subroomAccess.subroomId, childId), eq(subroomAccess.userId, b.userId)))).length, 0);
    const revokedClient = new Realtime({ tokenDetails: oldToken, logLevel: 0, queueMessages: false }); clients.push(revokedClient);
    await assert.rejects(() => revokedClient.channels.get(conversationChannel(chatId)).attach());
    const fresh = await makeInvite();
    await joinRoomInvite(db, b, fresh.token);
    await hallScope(db, b, childChatId);
    await withdrawRoomMember(db, b, roomId, b.userId);
    assert.equal((await member()).length, 0, "Member can leave");
    assert.equal((await db.select().from(roomMemberships).where(and(eq(roomMemberships.roomId, roomId), eq(roomMemberships.userId, a.userId))))[0].role, "owner");
    console.log("PASS: Room management permissions, duplicate joins, revoked invite denial, owner safety, failed-revocation rollback, serialized token/removal race, old-token rejection, access withdrawal, retained history and valid-invite rejoin/leave.");
  } finally {
    clients.forEach((client) => client.close());
    await db.delete(rooms).where(and(eq(rooms.id, roomId), eq(rooms.slug, slug)));
  }
}
main().then(() => process.exit(0)).catch((error: unknown) => { console.error("FAIL: MS7.1.2 lifecycle acceptance", { location: error instanceof Error ? error.stack?.match(/verify-room-lifecycle\.ts:\d+:\d+/)?.[0] : undefined }); process.exit(1); });
